### ISSUE TITLE
P25 TG add

### ISSUE THREAD

**Issue by NZ6D** [g4klx/P25Clients#110]
Hell, could you please add the following talk group to the P25Host file?

858   nz6d.dx40.com    41000

It has been up for several years now and I am just getting around to asking.

Than you,
David Griffith NZ6D

**Comment by NZ6D** [comment]
i meant Hello...

**Comment by g4klx** [comment]
No problems, added.
Jonathan  G4KLX

    On Thursday, 28 May 2020, 00:00:51 BST, NZ6D <notifications@github.com> wrote:  
 
 


Hell, could you please add the following talk group to the P25Host file?

858 nz6d.dx40.com 41000

It has been up for several years now and I am just getting around to asking.

Than you,
David Griffith NZ6D
