### ISSUE TITLE
Question: Default Reflector

### ISSUE THREAD

**Issue by mrickey** [g4klx/P25Clients#122]
I know I can set a Startup reflector in P25Gateway.ini. Is there a way to make this a default reflector.

I would like to have the gateway reconnect to the Startup reflector after a period of inactivity on a different reflector.

For example, let's say Startup is set to 10200. Someone keys up on 10300 and has a conversation. After a period of inactivity (10 minutes), the gateway would reconnect to 10200.

I found InactivityTimeout in the P25Fateway.ini file, but I can't figure out what it does. The only reference I see for it is in Conf.cpp. And, there are no comments about it's intended use.

Thanks in advance,
Michael AF6FB

**Comment by g4klx** [comment]
From what I remember the InactivityTimeout should do what you want. It changes the current reflector to the one  The time used in InactivityTimeout is in minutes, and will change the reflector to the value in the Startup field after no RF activity on that reflector for that period of time. RF users can change the chosen reflector at any time, they don't need to wait for that timeout.
Jonathan  G4KLX

    On Thursday, 30 July 2020, 17:47:05 BST, Michael Rickey <notifications@github.com> wrote:  
 
 


I know I can set a Startup reflector in P25Gateway.ini. Is there a way to make this a default reflector.

I would like to have the gateway reconnect to the Startup reflector after a period of inactivity on a different reflector.

For example, let's say Startup is set to 10200. Someone keys up on 10300 and has a conversation. After a period of inactivity (10 minutes), the gateway would reconnect to 10200.

I found InactivityTimeout in the P25Fateway.ini file, but I can't figure out what it does. The only reference I see for it is in Conf.cpp. And, there are no comments about it's intended use.

Thanks in advance,
Michael AF6FB

**Comment by mrickey** [comment]
Thanks Jonathon

*Michael Rickey* - AF6FB

949-298-0529 (*voice, sms, duo*)
michael.rickey@gmail.com
http://mrickey.net
