### ISSUE TITLE
Please add 226 (YO Romania) and 2263 (YO3 Bucharest) to the P25 reflector list

### ISSUE THREAD

**Issue by yo3cat** [g4klx/P25Clients#123]
Good afternoon.

Please add the following 2 reflectors to the P25 reflector list

226 p25.dstar-yo.ro 41000 (Romania YO P25 Network)
2263 p25.dstar-yo.ro 41000 (Bucharest YO3 P25 Network)

Thank you very much 
Catalin - YO3CAT

**Comment by g4klx** [comment]
Done

**Comment by yo3cat** [comment]
Thanks a lot

 

-----

’73 de YO3CAT

 

Vatra, Catalin Mihai

+40 (722) 514073

yo3cat@dstar-yo.ro

D-Star YO - Team

D-Star YO - Network Status

**Comment by yo3cat** [comment]
When do you expect to be visible in Pi-Star Hostlist?

Thanks
Catalin

**Comment by g4klx** [comment]
I don't know. Ask Pi-Star. I'd guess within 24 hours or so, but that is only a guess.

    On Friday, 31 July 2020, 13:11:43 BST, Catalin Vatra <notifications@github.com> wrote:  
 
 


When do you expect to be visible in Pi-Star Hostlist?

Thanks
Catalin

**Comment by yo3cat** [comment]
Thnka you 

Catalin

 

 

 

-----

’73 de YO3CAT

 

Vatra, Catalin Mihai

+40 (722) 514073

yo3cat@dstar-yo.ro

D-Star YO - Team

D-Star YO - Network Status
