### ISSUE TITLE
Add to P25Hosts.txt

### ISSUE THREAD

**Issue by kk6rq** [g4klx/P25Clients#124]
Hi,

Can you add my P25Reflector to the master file please?

11069   173.26.181.228    41000

It's *technically* a DHCP address, but it hasn't changed in 5 years, plus I intend to move it to the cloud eventually, at which time I'll advise the changes. Thanks.

-Bob
KK6RQ

ps. I hope this is the right place to post this and I apologize if it isn't...

**Comment by g4klx** [comment]
Done

**Comment by kk6rq** [comment]
Hey, small change to the comment portion of my P25 Reflector listing for 11069: Can you plz change it to:

# 11069 KK6RQ P25 Bridge to KK6RQ DMR-310551

At your convenience! 

Thanks,

Bob
KK6RQ
