### ISSUE TITLE
Update PAPA Reflectors

### ISSUE THREAD

**Issue by mrickey** [g4klx/P25Clients#125]
We decided to change our reflector ID so it matches our DMR TG. Also to add a reflector that is not bridged to our analog system.

Please update as follows:

# 31077 PAPA Chat - a place for PAPA members to chat http://papasys.com
31077	216.240.173.55	41000

# 31078 PAPA Bridge (bridged to analog) (formerly 7272) http://papasys.com
31078	216.240.173.55	41000

Thank you,
Michael

**Comment by g4klx** [comment]
Done.

**Comment by mrickey** [comment]
After I was given this update they changed one of the port numbers. 31078 changed to port 41007. Pull request will be made in a few minutes
