### ISSUE TITLE
Please add South Jersey P25 Talkgroup

### ISSUE THREAD

**Issue by N2ICV** [g4klx/P25Clients#15]
Hi John 
Can you please add
 South Jersey   31341  p25.kc2idb.net  41000  http://p25.kc2idb.net

Thanks Mike N2ICV

**Comment by g4klx** [comment]
Done, at last!

**Comment by N2ICV** [comment]
Thanks😃


Michael W. Andrescavage Sr

N2ICV

n2icv@hotmail.com<mailto:n2icv@hotmail.com>













________________________________
