### ISSUE TITLE
p25 host file

### ISSUE THREAD

**Issue by KN4UVP** [g4klx/P25Clients#154]
The Technology First p25 reflector TG 204 has been up dated.

Can you please change the p25 host file to:

w8ufo.ham shack.info port 41000

Many thanks

**Comment by g4klx** [comment]
That isn't a valid line for the host file. Can you check the hostname, it isn't valid.

**Comment by KN4UVP** [comment]
Dear Jonathan

 

My apologies for a typo in the host name it should be:

w8ufo.hamshack.info    port 41000 

for the Technology First TG 204 p25 reflector

 

Regards

Ronald KN4UVP

**Comment by g4klx** [comment]
Done
