### ISSUE TITLE
P25 Reflector Host File Addition

### ISSUE THREAD

**Issue by ve6en** [g4klx/P25Clients#155]
Hi Jonathan
Could you please add the follow new P25 Reflector to the "global" P25Hosts file:

3026 3026.hamshack.info 41000

Many thanks and Kind Regards
Andrew VE6EN/M0GRU

**Comment by g4klx** [comment]
What is TG3026, more information would be nice so that people knew what it was.

**Comment by ve6en** [comment]
My apologies I should have been more specific. TG 3026 is for the province of Alberta Canada. With a future crosslink to XLX196.

**Comment by g4klx** [comment]
Updated
