### ISSUE TITLE
Reflector IP change

### ISSUE THREAD

**Issue by kk6rq** [g4klx/P25Clients#156]
Hi,

Can you change the IP associated with 11069 to 173.21.251.157 please?

I'll be switching my setup over to dynamic DNS shortly, so I don't see this becoming a habit.
Thanks.

-Bob
KK6RQ

**Comment by kk6rq** [comment]
Update-- Got the DDNS setup; it's area52.zapto.org.

Thanks,
-Bob
KK6RQ

**Comment by g4klx** [comment]
Done
