### ISSUE TITLE
Please add P25 Reflector TG10406

### ISSUE THREAD

**Issue by psulions** [g4klx/P25Clients#169]
Hi G4KLX,

Can you please add the following TG for P25?

10406        p25.zj.digital       41000

Thank you!
BH5HUT 73

**Comment by g4klx** [comment]
Done, But I'd like to know more about this reflector.

**Comment by psulions** [comment]
Yes, This talk group is for P25 in Zhejiang province. This TG is bridged with DMR TG 46055. 
Let me know if you want more info.

Appreciate all you have done for the community!

**Comment by g4klx** [comment]
Thank you for that information. I've updated the entry in the hosts file.

Thanks
