### ISSUE TITLE
G4KLX OM, please register NXDNReflector and 25Reflector.

### ISSUE THREAD

**Issue by HL1RR** [g4klx/P25Clients#177]
G4KLX OM, please register NXDNReflector and 25Reflector.

[NXDN]
TG = 45000
Port = 41400
IP=nxdn.dvham.com
KOREA TG45000

[P25]
TG = 45000
port = 41000
IP = p25.dvham.com
KOREA TG45000

Thank you.
de HL1RR/LIM  73 !!

# 45000 KOREA TG45000
45000 nxdn.dvham.com             41400

# 45000 KOREA TG45000
45000   p25.dvham.com           41000

**Comment by g4klx** [comment]
Done for P25
