### ISSUE TITLE
 please add p25 reflector

### ISSUE THREAD

**Issue by jots76** [g4klx/P25Clients#184]
Dear Sir
Could you please add p25 reflector of Thailand  for pistar 
Info as below

1. P25 TG Number : 138 ; Description : P25 PKT THAILAND
    = 138 e23jwe.ddns.net 41001
2. P25 TG Number : 52138 ; Description : P25 Link Thailand
    = 52138 e23jwe.ddns.net 41000

Thanks

**Comment by g4klx** [comment]
Done

**Comment by jots76** [comment]
Dear Sir
Could you change host my p25 reflector and NXDNReflector Info as below

1. P25 TG Number : 138 ; Description : P25 PKT THAILAND
   = from e23jwe.ddns.net port 41001 to p25138.freeddns.org port 41001

2. P25 TG Number : 52138 ; Description : P25 Link Thailand
   = from 52138 e23jwe.ddns.net port 41000 to p2552138.freeddns.org port 41000

3.  [NXDN] TG Number = 138  ; Description : TG138 Thailand
    = from e23jwe.ddns.net port 41400 to nxdn138.freeddns.org port 41400

Thank you.
de E23JWE 73 !!
