### ISSUE TITLE
P25Hosts.txt

### ISSUE THREAD

**Issue by nessenj** [g4klx/P25Clients#186]
Curious what the process is for adding a new reflector into P25Hosts.txt?  I submitted a pull request to merge my changes with the Update P25Hosts.txt file, but after the merge was complete, I am still not seeing my reflector in the main P25Hosts.txt file.  Do I need to submit another pull requests for that file, or do changes made in Update P25Hosts.txt autotmatically make their way over to P25Hosts.txt

Thanks!

**Comment by g4klx** [comment]
If you see your change in the P25 Hosts file here, then it should appear for everyone.
