### ISSUE TITLE
Speach

### ISSUE THREAD

**Issue by cwfuselier** [g4klx/P25Clients#19]
Have a question, How to add an audio connect message when someone connects to my P25 reflector?

**Comment by g4klx** [comment]
You can't. I only had a limited number of P25 announcements which I "borrowed" from P25NX. Now that I know that full-rate AMBE is compatible with IMBE, I can reprocess the sound files that I use for D-Star, DMR, NXDN, to P25. This will mean that you lose "Pacific" and gain "Linked to 10400" or something similar. I can give you no ETA for this work though,
