### ISSUE TITLE
Please register P25Reflector

### ISSUE THREAD

**Issue by sp7lak** [g4klx/P25Clients#207]
Hello G4KLX

Please add the following host to the P25 Hosts list:

TG = 26078
Port = 41000
Reflector IP/Domain : p25.hblink.kutno.pl
Description: Poland HBLink Network

Thank you very much.
Krzysztof SP7LAK

**Comment by g4klx** [comment]
Done

**Comment by 91KMBDO** [comment]
Hello G4KLX

Please add the following host to the P25 Hosts list:

TG = 5155
Port = 41000
Reflector IP/Domain : 103.250.10.13
Description: Indonesia P25 Network

Thank you very much.
Wijaya YD6HQN
