### ISSUE TITLE
Plaese change P25Reflector Hosts 

### ISSUE THREAD

**Issue by jots76** [g4klx/P25Clients#217]
Dear Sir
Could you change my hosts p25 reflector Info as below

P25 TG Number : 138 ; Description : P25 PKT THAILAND
= from e23jwe.ddns.net port 41001 to p25138.freeddns.org port 41001

P25 TG Number : 52138 ; Description : P25 Link Thailand
= from 52138 e23jwe.ddns.net port 41000 to p2552138.freeddns.org port 41000

Thank you.
de E23JWE 73 !!

**Comment by g4klx** [comment]
Done
