### ISSUE TITLE
Please add P25Hosts txt

### ISSUE THREAD

**Issue by WA6JAY** [g4klx/P25Clients#222]
Please add P25Hosts  51503   149.28.201.109.    port 4569

**Comment by g4klx** [comment]
Can you give more information about this reflector please. Look at the existing hosts entries and provide the same information please.

**Comment by WA6JAY** [comment]
Hi Jonathan I am new to this I just want to create a p25 Tg for my fellow amateur ham. So I don’t know really know how. The information that I gave you is a talk group number and the IP address is from a dvswitch account of my friend. I have really no idea of what im doing I just want to have our own P25 talk group.
If you can give me all the info so I can give it to you or if you can kindly my one for us. Just in case you can make one for my group can you name it … US Philippines P25 network. Thank very much Jonathan.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by g4klx** [comment]
That's great. I've added your new reflector.
