### ISSUE TITLE
Please add TG 37225

### ISSUE THREAD

**Issue by WA3PNY** [g4klx/P25Clients#250]
Please Add TG 37225     3.215.215.169 port 41011
Requested name:  Haiti
Owner Organization : Haiti Digital Communications League (HDCL) P25
Owner : Johnny hh2mjf@yahoo.com

Thanks, PennLink Group will be hosting this reflector for them.
Jeff - WA3PNY  Thanks for all you do.

**Comment by g4klx** [comment]
Done

**Comment by WA3PNY** [comment]
Thanks Jonathan,

Have a wonderful holiday!

Jeff

Jeffrey V. Bauer
6381 Mulberry Ln.
Macungie, PA 18062
WA3PNY
CCS-7 3142263
NXDN 504
Wires-X 18394/28394
AllStar 529600
