### ISSUE TITLE
TG 37225 P25Hosts.txt file has entry error

### ISSUE THREAD

**Issue by WA3PNY** [g4klx/P25Clients#261]
Sorry for this change request.

The PiStar P25Hosts.txt file has 37225  3.215.215.169  port

Should be 37225   3.215.215.169   41011

Thanks and happy holidays

**Comment by N6DOZ** [comment]
Created pull request #268 to remove "**port**" from line

37225 3.215.215.169 **port** 41011

making it:

37225 3.215.215.169 41011


https://github.com/g4klx/P25Clients/pull/268
