### ISSUE TITLE
Please change existing TG 311969 to TG 51526 - omega25.ddns.net 41000

### ISSUE THREAD

**Issue by cutebasiya** [g4klx/P25Clients#262]
Please change TG 311969 to TG 51526
New TG request to add to the list 
P25 TG Number : 51526 ; Description : P25 Omega Communications = omegap25.ddns.net 41000

Owner Organization : Omega Communications
Owner : Marcy
Email: omegaradioclub@yahoo.com
Thanks, 73
KE6YEP

**Comment by N6DOZ** [comment]
This has been remedied. Please close. Thank you. 7-3 N6DOZ
