### ISSUE TITLE
P25 Host Reflector Update Please

### ISSUE THREAD

**Issue by ae4ml** [g4klx/P25Clients#291]
Please add this to the next update. 
Thank you 

Mike AE4ML

 10901     Randin.Org     41000

**Comment by g4klx** [comment]
Can you give me more details of this reflector please?

**Comment by ae4ml** [comment]
P25 Group Culpeper VA

**Comment by g4klx** [comment]
A name I know well! I used for to work for SWIFT before I did any digital voice stuff.

All done
