### ISSUE TITLE
P25 Reflector Reques for TG46010

### ISSUE THREAD

**Issue by bh1nyr** [g4klx/P25Clients#331]
Hello,

Could you please add p25 reflector to pistar database?

P25 TG Number : 46010 ;
Description : P25 Link XLX074 Modules A / BM TG46010 ;
Address: p25.bh1nyr.net ;
Port: 41000 ;
Location: Beijing, China ;

Thanks in advance!

73, BH1NYR

**Comment by g4klx** [comment]
Done
