### ISSUE TITLE
P25 Reflector Modify for TG#46010

### ISSUE THREAD

**Issue by bh1nyr** [g4klx/P25Clients#333]
Hello g4klx,

Due to problem of DNS, I would like to modify the address of p25 reflector TG#46010 as follow: 

P25 TG Number : 46010 ;
Description : P25 Link XLX074 Modules A / BM TG46010 ;
Address: 101.89.136.112 ;
Port: 41000 ;
Location: Beijing, China ;

Thanks in advance!

73, BH1NYR

**Comment by g4klx** [comment]
Done
