### ISSUE TITLE
Please add Taiwan P25 Talkgroup

### ISSUE THREAD

**Issue by davidcien** [g4klx/P25Clients#34]
Dear Sir 
Could you please add p25 reflector of Taiwan in the list for pistar user update ? Info as below 
10404 p25tw338.ddns.net 41000

I had update this info to P25Hosts.txt and it  already merged 

Thanks

**Comment by phl0** [comment]
It is already contained in P25Hosts as per your PR. See: https://github.com/g4klx/P25Clients/commit/799a8fc727d4b15ba0c2d1f8554e559301382832

**Comment by davidcien** [comment]
Dear Sirthanks a lot .i saw it .
by the way .may i know how  to change this  Description  of 10404 ? i need to contact to pi-star admin ?
sorry to brother you 



      寄件者： Florian (DF2ET) <notifications@github.com>
 收件者： g4klx/P25Clients <P25Clients@noreply.github.com> 
副本： davidcien <davidchien0327@yahoo.com.tw>; Author <author@noreply.github.com>
 寄件日期： 2019/3/24 (週日) 2:27 PM
 主旨： Re: [g4klx/P25Clients] Please add Taiwan P25 Talkgroup (#34)
   
It is already contained in P25Hosts as per your PR. See: 799a8fc—

**Comment by davidcien** [comment]
Dear Sir
thanks a lot .i saw it .
