### ISSUE TITLE
Request for P25 Reflector Modiffy TG#52072

### ISSUE THREAD

**Issue by phudit787** [g4klx/P25Clients#353]
Hello g4klx,

 May I trouble you to modify the address and description of P25 reflector TG#52072 as follow:

P25 TG Number :  52072
Description :  # Phuket P25 <>FreeDMR<>Echolink
Address:  203.170.129.69
Port: 41000 
Location:  Phuket Island,Thailand

Many thank you.
Best 73,
HS2ZY

**Comment by g4klx** [comment]
Done
