### ISSUE TITLE
please add  TG:20222 Reflector

### ISSUE THREAD

**Issue by sv2snh** [g4klx/P25Clients#365]
https://github.com/g4klx/P25Clients/blob/c36635e07cee28e235d6169f4d1885330b77d221/P25Gateway/P25Hosts.txt#L332
Hi Jonathan,please add TG:20222   p25-frn.ddns.net   Port 41000   HELLAS-FRN.Thx 73 de SV2SNH  GR.

**Comment by g4klx** [comment]
Done
