### ISSUE TITLE
Please add P25Reflector to the host list

### ISSUE THREAD

**Issue by W3KIT-910** [g4klx/P25Clients#375]
Hello, please submit 137 to the P25 host list.

137 p25a.mywire.org 41000

XLX 137

Thank you kindly,

Kit W3KIT

**Comment by g4klx** [comment]
Could you provide more details than just XLX137 please. Look at other entries and try and match the level of detail.

**Comment by W3KIT-910** [comment]
> Could you provide more details than just XLX137 please. Look at other entries and try and match the level of detail.

Sure, I could do that.

137 p25a.mywire.org 41000

XLX137 Module A Link to YSF79655

Thank you,
Kit

**Comment by g4klx** [comment]
Done
