### ISSUE TITLE
PLEASE UPDATE TG-7941

### ISSUE THREAD

**Issue by KE6GVK** [g4klx/P25Clients#385]
https://github.com/g4klx/P25Clients/blob/fb963a409b979cd59b7564f863b972d98af61f28/P25Gateway/P25Hosts.txt#L192

# 7941 WHITE MOUNTAIN REPEATER ASSOCIATION
7941	45.63.48.117    41000

Thanks HAPPY NEW YEAR
MIKE - KE6GVK

**Comment by g4klx** [comment]
Done
