### ISSUE TITLE
Can you please add my P25 reflector to the host list

### ISSUE THREAD

**Issue by KM4GDU** [g4klx/P25Clients#387]
This is Carl KM4GDU
Reflector Name "North Carolina NCC-1701"

NCC-1701-P25.ddns.net
Port 41001
TG 22222

We currently have 1 linked 440 repeater N4JDW in Wilmington NC. The frequency is 444.050 with a NAC of 293
we have a Facebook Group with 72 members
https://www.facebook.com/groups/1317232475787215/

**Comment by g4klx** [comment]
Done
