### ISSUE TITLE
P25 Reflector

### ISSUE THREAD

**Issue by jasonshatto** [g4klx/P25Clients#407]
I'm looking to setup a P25 reflector in the cloud.  We had this running several years ago.  I'm not seeing the software to install.  Are you able to point me in the right direction for this?

**Comment by g4klx** [comment]
The P25 Reflector, along with all of my other reflectors has been taken over by Doug AD8DP, he will provide support from now on.

**Comment by yl3im** [comment]
Thank you very much! Does he have a GitHub repo? Can't find it myself.

**Comment by g4klx** [comment]
Here you go: https://github.com/nostar/DVReflectors
