### ISSUE TITLE
P25Hosts update - 555 domain name change

### ISSUE THREAD

**Issue by ga900p25** [g4klx/P25Clients#479]
Please change the domain name and narrative associated with TG555. 

CURRENT
# 555 Georgia 900 P25-ASL Xlink
555	georgia900p25.hopto.org	41000

NEW
# 555 Georgia 900 P25
555	georgia900p25.us	41000

https://github.com/g4klx/P25Clients/blob/30879a0f047f41470783370ec9b7de0a3d28ecc0/P25Gateway/P25Hosts.txt#L70

Thanks,
Ken
W4NOC

**Comment by g4klx** [comment]
Done
