### ISSUE TITLE
wrong record in P25 Hostlist

### ISSUE THREAD

**Issue by hb9gfx** [g4klx/P25Clients#489]
Hi Jonathan,

I found a wrong record in the P25 Hosts list
Maybe I reported it wrong

wrong:
# 26447 P25 XLX-OWL
26447 p25.xkx-owl.de 41000

correct:
# 26447 P25 XLX-OWL
26447 xlx-owl.de 41000

thanks for changing
73 de Stefan HB9GFX

**Comment by g4klx** [comment]
Fixed
