### ISSUE TITLE
TG P25 numbering change

### ISSUE THREAD

**Issue by mikithd** [g4klx/P25Clients#494]
Good afternoon,
this to request the move of the Reflector P25 TG 22487 to TG 22208 with TAG Italy Centro-Digiland. Specifically, remove the following reflector:

.   # 22487 IT - Italy Centro
22487	famiuse.ddns.net	41000

and enter the following:

.   # 22208 IT - Italy Centro/Digiland
22208	famiuse.ddns.net	41000

This change is to standardize our entire multi-protocol network towards a single numbering as we recently had a new TG with the same numbering.

In thanking you for your work and apologizing for the inconvenience, I cordially greet you.

IZ0THD, Michele

**Comment by g4klx** [comment]
Done

**Comment by mikithd** [comment]
Grazie tante.

73, IZ0THD

Il dom 24 mar 2024, 16:33 Jonathan Naylor ***@***.***> ha
scritto:
