### ISSUE TITLE
Change of IP address and TAG TG 22208

### ISSUE THREAD

**Issue by mikithd** [g4klx/P25Clients#527]
Good afternoon,
this to request, where nothing prevents, a variation to the P25 TG 22208 reflector as follows:

Refelctor currently active:
# 22208 IT - Italy Centro
22208	famiuse.ddns.net	41000

to be replaced with:
#22208 IT Italy Centro Digiland
22208    185.205.209.70    41000

Thank you for the work you do for us and for your availability.

IZ0THD

**Comment by g4klx** [comment]
This was covered in your pull request I think, so it should now be in the P25 hosts file.

**Comment by mikithd** [comment]
yes, it was for the same reason.  Thank you

Il gio 4 lug 2024, 19:42 Jonathan Naylor ***@***.***> ha
scritto:
