### ISSUE TITLE
P25Gateway fails to load if ipv6 is disabled at the kernel level

### ISSUE THREAD

**Issue by w1bsb** [g4klx/P25Clients#546]
I have IPv6 disabled at the kernel level (ipv6.disable=1) on a rapsberry pi. When I try to load P25Gateway, it is unable to bind port 42010 on the IPv6 ANY address (::) and fails to continue loading.  P25Gateway loads as normal when IPv6 is enabled.  It should still load if IPv6 is disabled. I believe the issue lies in CP25Network::open()

**Comment by g4klx** [comment]
I don't understand not enabling IPv6 in this date and age.

I could fix it, but I see no point doing so. Sorry.
