### ISSUE TITLE
P25 Reflector Addition

### ISSUE THREAD

**Issue by 4f7dad** [g4klx/P25Clients#70]
Greatings from the Philippines.

Can you please add our P25 Reflector to the list?

address: 140.82.14.24
port: 41000
talkgroup: 51575
description: PH-Dumaguete Link

This reflector is currently link to YSF and DMR (BM 51575).

Thank you and 73.
Dan, 4F7DAD

**Comment by g4klx** [comment]
Hi Dan

I've added it.

Jonathan  G4KLX

**Comment by 4f7dad** [comment]
Thanks a lot.  Sorry I got no other means of getting in touch with you.  You can remove this thread from the Issues tab.  Thanks again.

Dan, 4F7DAD
