### ISSUE TITLE
New P25 Reflectors at XLX045

### ISSUE THREAD

**Issue by WA3PNY** [g4klx/P25Clients#80]
There are two new reflectors for P25 on XLX045 it would be helpful if they could be added to the P25Hosts.txt file.  I have checked them both out and they are operational.

# XLX045E P25 <-> DMR/DSTAR/YSF/NXDN                                            
6       70.44.20.24     41000                                                   
# XLX045A P25 <-> DMR/DSTAR/YSF/NXDN <-> BM TG31425 PA Wide Cross Mode          
31425   70.44.20.24     41001 

Thanks
Jeff, WA3PNY - Sysop XLX045

**Comment by g4klx** [comment]
Done
