### ISSUE TITLE
TG 51575 Description

### ISSUE THREAD

**Issue by 4f7dad** [g4klx/P25Clients#85]
Hello Jonathan,

Please revise the description for TG 51575 from:
"PH-Dumaguete Link to YSF and DMR (BM 51575)" to
"PH-Dumaguete Link (Multimode)"

There is interest in bridging it to another DMR talkgtoup on a scheduled basis.

Thank you.

73
Dan, 4F7DAD

**Comment by g4klx** [comment]
Done
