### ISSUE TITLE
Parrot TX Audio is chopped

### ISSUE THREAD

**Issue by AndyTaylorTweet** [g4klx/P25Clients#9]
In the latest build - the P25 Parrot appears to receive the audio fine, BUT the TX audio from the parrot is chopped into a small transmissions, the audio is there but garbled too.

**Comment by g4klx** [comment]
Whoops. Sorry. Do a new pull, it should be back to normal.

**Comment by AndyTaylorTweet** [comment]
Bizarely that didn't seem to fix is - I rolled back through a few versions of the parrot and unless I am missing something - this problem doesn't seem to be related to the parrot software specifically - before you dig too far into this - I'll try stepping back through a few revisions myself and try to help pin-point the failure more accurately

**Comment by AndyTaylorTweet** [comment]
Removed my last comment, it turned out to be totally garbage;
I pulled in the reversion correctly and built the binaries and we're back in business - thank you!
